<?php
session_start();
require '../db_conn.php'; // Provides $conn and database constants

// Ensure admin is logged in
if (!isset($_SESSION['id'], $_SESSION['username'], $_SESSION['userType']) || $_SESSION['userType'] !== 'admin') {
    header("Location: ../admin-portal.php");
    exit();
}

// Helper function to dump database using PHP (fallback if mysqldump is unavailable)
function php_dump($conn, $db_name) {
    $output = "-- Database backup generated by PHP fallback on " . date('Y-m-d H:i:s') . "\n";
    $output .= "-- --------------------------------------------------\n\n";
    $output .= "CREATE DATABASE IF NOT EXISTS `$db_name`;\n";
    $output .= "USE `$db_name`;\n\n";

    // Get all tables
    $tables = $conn->query("SHOW TABLES");
    while ($row = $tables->fetch_array()) {
        $table = $row[0];
        $output .= "-- Table structure for table `$table`\n";
        $output .= "DROP TABLE IF EXISTS `$table`;\n";

        // Get CREATE TABLE statement
        $create = $conn->query("SHOW CREATE TABLE `$table`")->fetch_assoc();
        $output .= $create['Create Table'] . ";\n\n";

        // Get table data
        $data = $conn->query("SELECT * FROM `$table`");
        if ($data->num_rows > 0) {
            $output .= "-- Dumping data for table `$table`\n";
            $columns = array_keys($data->fetch_assoc());
            $data->data_seek(0);

            while ($rowData = $data->fetch_assoc()) {
                $values = array_map(function($value) use ($conn) {
                    return $value === null ? 'NULL' : "'" . $conn->real_escape_string($value) . "'";
                }, array_values($rowData));
                $output .= "INSERT INTO `$table` (`" . implode('`, `', $columns) . "`) VALUES (" . implode(', ', $values) . ");\n";
            }
            $output .= "\n";
        }
    }
    return $output;
}

// ---------- BACKUP ----------
if ($_SERVER['REQUEST_METHOD'] === 'GET') {
    // Get database credentials from constants or fallback
    $db_host = defined('DB_HOST') ? constant('DB_HOST') : 'localhost';
    $db_user = defined('DB_USER') ? constant('DB_USER') : 'root';
    $db_pass = defined('DB_PASS') ? constant('DB_PASS') : '';
    $db_name = defined('DB_NAME') ? constant('DB_NAME') : 'grade_assist';

    // Try to use mysqldump first
    $use_mysqldump = true;
    $output = null;
    $return_var = null;

    // Check if mysqldump is available
    if (function_exists('shell_exec')) {
        $check = shell_exec('command -v mysqldump 2>/dev/null');
        if (empty($check)) {
            $use_mysqldump = false;
        }
    } else {
        $use_mysqldump = false;
    }

    if ($use_mysqldump) {
        // Build command
        $command = sprintf(
            'mysqldump --host=%s --user=%s --password=%s %s 2>&1',
            escapeshellarg($db_host),
            escapeshellarg($db_user),
            escapeshellarg($db_pass),
            escapeshellarg($db_name)
        );

        // Execute and capture output + return code
        exec($command, $output, $return_var);
        $sql_content = implode("\n", $output);
    }

    // If mysqldump failed or not available, use PHP fallback
    if (!$use_mysqldump || $return_var !== 0) {
        $sql_content = php_dump($conn, $db_name);
        // Log that fallback was used (optional)
        error_log("Backup: used PHP fallback (mysqldump failed or not available)");
    }

    // Set headers for download
    header('Content-Type: application/octet-stream');
    header('Content-Disposition: attachment; filename="GradeAssist_' . date('Y-m-d_H-i-s') . '.sql"');
    header('Pragma: no-cache');
    header('Expires: 0');
    header('Content-Length: ' . strlen($sql_content));
    echo $sql_content;
    exit();
}

// ---------- RESTORE ----------
if ($_SERVER['REQUEST_METHOD'] === 'POST') {
    // Verify admin password
    $admin_id = $_SESSION['id'];
    $entered_password = $_POST['admin_password'] ?? '';

    $stmt = $conn->prepare("SELECT password FROM users WHERE id = ? AND userType = 'admin'");
    $stmt->bind_param('i', $admin_id);

    $stmt->execute();
    $result = $stmt->get_result();
    $admin = $result->fetch_assoc();

    // Hash the entered password using MD5 (same as login)
    $entered_password_hash = md5($entered_password);

    if (!$admin || $entered_password_hash !== $admin['password']) {
        $_SESSION['message_danger'] = "Incorrect admin password. Restore cancelled.";
        header("Location: backup.php"); // Adjust filename if needed
        exit();
    }

    // Validate uploaded file
    if (!isset($_FILES['sql_file']) || $_FILES['sql_file']['error'] !== UPLOAD_ERR_OK) {
        $_SESSION['message_danger'] = "File upload error. Please select a valid .sql file.";
        header("Location: backup.php");
        exit();
    }

    $file_tmp = $_FILES['sql_file']['tmp_name'];
    $file_name = $_FILES['sql_file']['name'];
    $file_ext = strtolower(pathinfo($file_name, PATHINFO_EXTENSION));

    if ($file_ext !== 'sql') {
        $_SESSION['message_danger'] = "Only .sql files are allowed.";
        header("Location: backup.php");
        exit();
    }

    $sql = file_get_contents($file_tmp);
    if ($sql === false) {
        $_SESSION['message_danger'] = "Could not read uploaded file.";
        header("Location: backup.php");
        exit();
    }

    // ----- WIPE EXISTING DATABASE (drop all tables) -----
    $conn->query("SET FOREIGN_KEY_CHECKS = 0");
    $tables = $conn->query("SHOW TABLES");
    if ($tables) {
        while ($row = $tables->fetch_array()) {
            $table = $row[0];
            $conn->query("DROP TABLE IF EXISTS `$table`");
        }
    }

    // ----- IMPORT THE NEW SQL -----
    $conn->query("SET autocommit=0");
    $conn->query("SET FOREIGN_KEY_CHECKS = 0");

    $result = $conn->multi_query($sql);
    $errors = [];

    if ($result) {
        do {
            if ($conn->error) {
                $errors[] = $conn->error;
            }
        } while ($conn->next_result());
    } else {
        $errors[] = $conn->error;
    }

    $conn->query("SET FOREIGN_KEY_CHECKS = 1");
    $conn->query("COMMIT");
    $conn->query("SET autocommit=1");

    if (empty($errors)) {
        $_SESSION['message'] = "Database restored successfully from " . htmlspecialchars($file_name);
    } else {
        $_SESSION['message_danger'] = "Restore failed: " . implode('; ', $errors);
    }

    header("Location: backup.php");
    exit();
}

// If no valid request, redirect back
header("Location: backup.php");
exit();